### ISSUE TITLE
I fail to get it to work with reactphp-curl

### ISSUE THREAD

**Issue by Reilaen** [clue/php-block-react#3] opened 2015-05-18 07:35 UTC
Hi there,

i have a bunch of curl calls that i want to finish before i process further to save memory while processing a lot of data. But somehow block halts everything for infinite time, so nothing happens anymore.

Even with trying it in a simple testcase with one curl request and awaitOne didn't work.

I am not sure if that is a issue because of as mistake on my part or if reactphp-curl is incompatible with block. I would be gratefull if you could help me to work this issue out. 

Best regards and have a nice day.

**Comment by clue** [comment] 2015-05-18 07:42
Hi @Reilaen, thanks for posting back. Personally, I'm not familiar with "reactphp-curl", but given this library only depends on React's `EventLoop`, I would have expected this to work nonetheless. Can you please provide a gist with your particular test case so that we can reproduce this?

**Comment by Reilaen** [comment] 2015-05-18 09:01
Hi thanks for your quick reply. While writing the testcase i found out that i was wrong and running basic awaitOne and awaitAll() does work as intended. The actual isse is that blocker inside a curl->get call locks itself up.

In order to reproduce it you can use this gist: https://gist.github.com/Reilaen/4b9b5a4c39be1fa58576

**Comment by clue** [comment] 2015-05-18 09:41
Thanks for your test case! Afaict this boils down to this:

```php
createPromise()->then(function() use ($loop) {
    $blocker = new Blocker( $loop );
    $blocker->awaitOne(createPromise());
});
$loop->run();
```

This is *not supported* at the moment, and I'm not sure we *can* support this.

What this does is that it already `run()`s the loop (last line) and the blocker internally tries to `run()` the loop as well.

Mixing async and blocking code should be avoided, as it leads to some difficult situations. In your particular case you should either not block within your promise resolution handler or also block on your outer promise and avoid calling `run()`.

Obviously, we should provide some more documentation on this… any volunteers? :)

**Comment by Reilaen** [comment] 2015-05-18 09:51
I know it is no good idea to add blocking in a non blocking environment. But i couldn't find another solution. I try to scrap lots of data and even with 1024MB of ram given to php it runs out of memory because of so running so many simultanious calls, so somehow i have to reduce it. Thats why i tried to part it into chunks of workload and block out the processiong till the chunk is worked off.

**Comment by clue** [comment] 2015-05-18 10:34
>  In your particular case you should either not block within your promise resolution handler – or also block on your outer promise and avoid calling run().

Does any of these two options help in your case?

If you want to execute in chunks of N parallel requests, you can probably rewrite your code to looks like this:

```
$blocker->awaitAll(createRequests($n));
$blocker->awaitAll(createRequests($n));
```

A better approach would probably be to use some kind of async task runner / job scheduler that limits the number of concurrent jobs (promises). Note that this is very likely out of scope for this library though.

**Comment by joshdifabio** [comment] 2015-05-18 10:47
@Reilaen I literally pushed something to GitHub two days ago to solve the same issue :). Check out [joshdifabio/resource-pool](https://github.com/joshdifabio/resource-pool/tree/allocate-then). The `[allocate-then branch](https://github.com/joshdifabio/resource-pool/tree/allocate-then)` will likely be merged to master and tagged in the next couple of days.

**Comment by clue** [comment] 2015-05-18 11:32
> @Reilaen I pushed something to GitHub two days ago to solve the same issue :). Check out joshdifabio/resource-pool.

Awesome job @Reilaen, looks great! :+1: 

I'm closing this for now, feel free to comment if the problem persists and we can reopen this.

**Closed by clue** 2015-05-18 11:32 UTC
Labels: question
